#以数组内开头的消息不上传
noMsgStart:
  - "示例1"

#包含了数组内的消息不上传
noMsgInclude:
  - 示例1

# 通知哪个主人 
howToMaster: 1

#断开连接时否通知主人
disconnectToMaster: false

#重新连接成功时是否通知主人
reconnectToMaster: false

#首次连接时是否通知主人成功还是失败
firstconnectToMaster: false

#消息存储时间,用于撤回和回复消息,单位秒
msgStoreTime: 600

#不需要开启的群
noGroup:
  - 123456